version: '3'

services:
  # app:
  #   image: node:18.14-alpine
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - 3000:3000
  #   command: yarn start:dev
  #   depends_on:
  #     - db

  db:
    image: postgres:14.3
    container_name: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - nest-started-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  nest-started-db:
    external: false